# Generated by Django 6.0 on 2025-12-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_branch_customuser_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission percentage (e.g. 5.00 for 5%)', max_digits=5),
        ),
    ]
