# Generated by Django 6.0 on 2025-12-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('ADD', 'Add'), ('REDUCE', 'Reduce'), ('SET', 'Set'), ('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('DISPOSAL', 'Disposal'), ('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired')], max_length=20),
        ),
    ]
