# Generated by Django 6.0 on 2025-12-26 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockmovement_movement_type'),
        ('shops', '0003_shop_public_visibility_shop_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='HappyHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Percentage off, e.g., 10.00 for 10%', max_digits=5)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days_of_week', models.CharField(default='0,1,2,3,4,5,6', help_text='Comma-separated days: 0=Mon, 6=Sun', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='happy_hours', to='inventory.category')),
                ('products', models.ManyToManyField(blank=True, related_name='happy_hours', to='inventory.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='happy_hours', to='shops.shop')),
            ],
        ),
    ]
