# Generated by Django 6.0 on 2025-12-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_is_public_happyhour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HappyHour',
        ),
    ]
