# Generated by Django 6.0 on 2025-12-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_address_shop_email_shop_phone_shop_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='public_visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
