# Generated by Django 6.0 on 2025-12-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_update_subscription_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsubscription',
            name='billing_cycle',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', '3 Months'), ('BIANNUALLY', '6 Months'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20),
        ),
    ]
