# Generated by Django 6.0 on 2026-01-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_shopsubscription_billing_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_products',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_users',
            field=models.IntegerField(default=5),
        ),
    ]
