# Generated by Django 6.0 on 2025-12-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salereturn_salereturnitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at']},
        ),
    ]
